version: '3'

tasks:
  setup:
    desc: Creates the needed NATS streams and key-value stores
    cmds:
      - kubectl exec deployments/nats-box -- nats stream add --defaults --subjects "accounts.commands.>" AccountsCommands
      - kubectl exec deployments/nats-box -- nats stream add --defaults --subjects "accounts.errors.>" AccountsErrors
      - kubectl exec deployments/nats-box -- nats stream add --defaults --subjects "accounts.events.>" AccountsEvents
      - kubectl exec deployments/nats-box -- nats kv add AccountsStore
  accounts:purge:
    desc: Purge Accounts streams and key-value store
    cmds:
      - kubectl exec deployments/nats-box -- nats stream purge -f AccountsEvents
      - kubectl exec deployments/nats-box -- nats kv del -f AccountsStore
      - kubectl exec deployments/nats-box -- nats kv add AccountsStore
  accounts:commands:view:
    desc: View AccountsCommands stream
    cmds:
      - kubectl exec -it deployments/nats-box -- nats stream view AccountsCommands
  accounts:events:view:
    desc: View AccountsErrors stream
    cmds:
      - kubectl exec -it deployments/nats-box -- nats stream view AccountsErrors
  accounts:errors:view:
    desc: View AccountsEvents stream
    cmds:
      - kubectl exec -it deployments/nats-box -- nats stream view AccountsEvents
  accounts:store:view:
    desc: View AccountsStore
    cmds:
      - kubectl exec -it deployments/nats-box -- nats kv ls AccountsStore
